### ISSUE TITLE
No connection available when switching access points

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1648]
Since AdGuard-Bot won't let me reopen issue #1576:

Quick update: I got a new WLAN repeater from AVM:

https://avm.de/produkte/fritzwlan/fritzrepeater-2400/

Which is connected to my FritzBox Cable 6591.

I noticed with a Speedtest app that as soon as the Connection switches from my router to my repeater the speed drops to 0 kbit's. These are exactly the WLAN dropouts which I still have when switching between WLAN and LTE and it's only happening when AdGuard DNS is enabled.

**Comment by iDjay** [comment]
Just to explain it a bit better:

- I'm connected with my router.
- Conenction changes to the repeater or LTE.
- I have no connectivity for about 1-2 seconds in normal cases (sometimes AdGuard DNS reconnects).
- In some cases I have no connectivity until the connection switches again or until I turn flight mode on and off.
- Everything works fine with AdGuard DNS disabled.
- Changing the DNS Tunnel / Mode doesn't help.
- Activating / deactivating the option to restart the connection when the network connection changes in AdGuard's settings doesn't help.
- Everything worked fine before iOS 14.

We had a similar issue a few years ago affecting CarPlay. Maybe the same problem?

**Comment by ameshkov** [comment]
Quick update - we just pushed a new beta - plz try with it.

**Comment by iDjay** [comment]
> Quick update - we just pushed a new beta - plz try with it.

Seems to be fixed, will do some more testing over the weekend.

**Comment by ameshkov** [comment]
> Seems to be fixed, will do some more testing over the weekend.

Yeah, the changes we made should've helped.

**Comment by iDjay** [comment]
Still happening sometimes:

AdGuard reconnects (I can see the VPN icon disappearing and reappearing) and the connection is not available for 2-3 seconds. 

The option to restart AdGuard when network connection changes is turned off.

**Comment by iDjay** [comment]
But I can definitely see some improvements, the battery drain is gone.

**Comment by ameshkov** [comment]
> AdGuard reconnects (I can see the VPN icon disappearing and reappearing) and the connection is not available for 2-3 seconds.

Hm, this may mean that the Tunnel crashes. You can check it here: Settings -> Privacy -> Analytics & Improvements -> look for reports starting with `Tunnel-` prefix.

**Comment by iDjay** [comment]
I can't find anything when I search for "tunnel".

**Comment by ameshkov** [comment]
Yep, I can confirm this issue:
https://github.com/AdguardTeam/AdguardForiOS/issues/1652
