### ISSUE TITLE
The vpn tunnel crashes during a long data exchange

### ISSUE THREAD

**Issue by Marco224** [AdguardTeam/AdguardForiOS#1656]
### Issue Details

During an operation that involves a continuous data exchange, such as a video call, the connection is interrupted and the vpn tunnel restarts, while in most contexts it is irrelevant, in other cases (such as a video call) it is quite frustrating to wait for 10/15 seconds in which the connection is re-established.

You can get the same effect by repeating a Speedtest several times
 
Changing the vpn tunnel mode or the restart when the network changes, does not help

- **AdGuard version:**
AdGuard Pro 4.0.3 (544)
- **Device model and storage size:**
iPhone XS 
- **Operating system and version:**
iOS 14.0.1

### Expected Behavior

Internet connection is not interrupted

### Actual Behavior
- Internet stops working
- The Wi-Fi signal drops to a minimum
- In the status bar appears in order: the icon 4g- vpn- 4g- Wi-Fi- 4g- vpn- Wi-Fi (sometimes the lap is repeated several times but I noticed that it is always the same)
- Internet connection is restored

### Video
- https://ufile.io/9tyak0rk

**Comment by Maxim-Butov** [comment]
Unfortunately I cant reproduce this bug with a speedtest and video call. 
To help us solve the problem, please enable "debug logs" in the settings->general->advanced settings, try reproduce the error and after that send the logs to **apple@adguard.com**.

**Comment by Marco224** [comment]
If I activate the debug logs, the vpn can't connect and break the connection until i turn the switch off. In any case i sent the log file with the "debug logs" turned off.

**Comment by Quorum75** [comment]
FYI I faced the same issue in the past and it has been solved #1613.

**Comment by iDjay** [comment]
Having a similar issue since months...

**Comment by zzebrum** [comment]
@Marco224 I'm very sorry for the late reply! Can you collect crash files from your device? go to Settings app - Privacy - Analytics & Improvements - Analytics Data and export AdGuad crash files

**Comment by Marco224** [comment]
Hi zebrum! I don't have any AdGuard crash file there in the analytics data, although it still happens to me a lot

**Comment by zzebrum** [comment]
@Marco224 I'm very sorry for the late reply! As a temporary solution, I'm suggesting you try the beta version.

**Comment by Marco224** [comment]
Using the beta version (566) the problem eases, the connection keeps dropping randomly causing the protection to be restarted, but it doesn't restart repeatedly as described above, so the internet is interrupted only for a couple of seconds

**Comment by Marco224** [comment]
At this point I do not know if the problem is only on my side

**Comment by zzebrum** [comment]
@Marco224 I'm trying to reproduce the problem. With what video call apps do you have this issue? Face time?

**Comment by Marco224** [comment]
@zzebrum It happens independently of the video call application used, because it is the internet connection that is interrupted because the vpn tunnel is repeatedly deactivated and reactivated and sometimes does not do so in time to re-establish the connection.

https://ufile.io/xdzvrbt9

In this case for example I was trying to reproduce the bug using a Speedtest, (look at the Wi-Fi icon), I was obviously not moving and with the AdGuard protection disabled the signal remains stable (two lines out of three) without passing repeatedly between 4g and Wi-Fi

**Comment by zzebrum** [comment]
@Marco224 does it happen in other networks too?

**Comment by Marco224** [comment]
@zzebrum At the moment I don't have the possibility to try with different Wi-Fi, but it happens with both Wi-Fi networks that I usually use.
Is it possible that the tunnel tends to restart when the Wi-Fi signal is not particularly strong?

**Comment by zzebrum** [comment]
@Marco224 

> Is it possible that the tunnel tends to restart when the Wi-Fi signal is not particularly strong?

yep, it is very likely what happens here. 
I'll assign the issue to v4.1. Will you send me logs at mg@adguard.com, please?

**Comment by Marco224** [comment]
I sent the log file :)

**Comment by Marco224** [comment]
Fixed in 4.1.0, thanks for your work

**Comment by Marco224** [comment]
@zzebrum I have to reopen it because the problem occurs again with version 4.1.0 (637), while it does not occur with version 4.1.0 (628)

When the Wi-Fi signal is not strong (two out of three bars) the VPN tunnel starts rebooting continuously, repeatedly interrupting the Internet connection 

I sent the log with debug mode enabled, between 16:41 and 16:47

**Comment by zzebrum** [comment]
@Marco224 I think it is related to https://github.com/AdguardTeam/AdguardForiOS/issues/1711#issuecomment-775843120
