### ISSUE TITLE
'Invalid Upstream' error when adding custom Secure DNS server

### ISSUE THREAD

**Issue by s-crypt** [AdguardTeam/AdguardForiOS#1815]
### Issue Details

- **AdGuard version:**
  - Adguard Pro for iOS 4.2.1
- **Device model:**
  - iPhone XR
- **Operating system and version:**
  - iOS 14.7.1
 
### Expected Behavior

New, custom DNS upstream is added to list of DNS servers

### Actual Behavior

Gives the error "You have entered the invalid upstream" 

### Additional Information

I tried to add `https://dns.nextdns.io/[code]` where [code] is my 6 character alphanumeric configuration ID within NextDNS.

**Comment by Aydinv13** [comment]
Does this error occur only with NextDNS servers?

**Comment by s-crypt** [comment]
The same error occurs when I manually enter

[Cloudflare's Public DNS](https://developers.cloudflare.com/1.1.1.1/dns-over-https/request-structure)
`https://cloudflare-dns.com/dns-query`

[Google's Public DNS](https://developers.google.com/speed/public-dns/docs/doh/)
`https://dns.google/dns-query`

[DNS.Watch](https://dns.watch/index)
`https://resolver2.dns.watch/dns-query`

[Quad9](https://quad9.net/service/service-addresses-and-features)
`https://dns.quad9.net/dns-query`
`tls://dns.quad9.net`

The error seemingly happens no matter the url or secure protocol (https/tls), so no custom DNS servers can be added

**Comment by Aydinv13** [comment]
Thanks for observations. We will fix it soon

**Comment by Eugene-Savenko** [comment]
More logs in Zendesk: 545937

**Comment by 08kovalchuk03** [comment]
It seems that we've already fixed this error, please check it when the new version is out. If the problem will persist let us know!

**Comment by DatBoiQraZy** [comment]
> It seems that we've already fixed this error, please check it when the new version is out. If the problem will persist let us know!

No, man! Just tried adding custom DNS for Surfshark. I’m using iOS BETA apps for Adguard (I’m Premium) and Adguard VPN - if that may be a hinderance!?!

**Comment by azafrak** [comment]
Hi,

I am using Adguard windows version. I will add private dns but I am getting the same error. When I type the private dns addresses of NextDNS, it gives an invalid address warning.

I don't understand what is the problem.

**Comment by thomasified** [comment]
Hi, I'm still encountering this issue on Adguard iOS 4.3.2 (938)

A simple work-around is to:
- Open iOS setting > VPN Tab
- Remove Adguard VPN Profile
- Go to DNS Protection tab > DNS Server > Add new DoH or DoT servers
- Now Adguard iOS won't show the "Invalid Upstream error" anymore
- Don't forget to set upstream DNS Server in Adguard iOS setting for DoH and DoT to work correctly.

Cheers.

**Comment by CPCer** [comment]
Same problem here with Adguard windows and Android. Could you just let the user take the responsibility of setting up DNS for themselves... @08kovalchuk03

**Comment by RainmakerRaw** [comment]
I realise this is closed as fixed, but I'm seeing this same issue on iOS 15.6.1 also. I wasn't sure whether to open a new bug or tack on to this one. Sorry if my netiquette is back to front. 

I'm using AdGuard Pro 4.4.3(961). I also have AdGuard VPN installed (v 2.0.6(13)). I can add AdGuard Private DNS to AdGuard Pro for iOS using QUIC with no problems. When I try to add NextDNS over QUIC with `quic://My--Device-12345.dns.nextdns.io` I get invalid upstream. If I switch the formatting around to `https://dns.nextdns.io/12345/My%20Device` it works OK. I see similar errors intermittently for my own AGH domain at `dns.mydomain.com` but it allows me to add it without error after a few tries. NextDNS just refuses to add at all, so I'm stuck with DoH.
