### ISSUE TITLE
iOS Widget "Unable to Load"

### ISSUE THREAD

**Issue by BaronKrause** [AdguardTeam/AdguardForiOS#1849]
AdGuard for iOS v4.3.0(876)
iPhone running iOS 15.1

I have the Testflight build of Adguard running on both my iPhone 11 and iPad Pro and noticed that the Widget on my iPhone was saying "Unable to Load" while the iPads widget worked properly (its still buggy, if you use it to disable blocking before opening the app, it will only open the app without disabling blocking, but the widget still reports it being disabled).

I uninstalled/rebooted and reinstalled Adguard via test flight on iOS and re enabled the widget and its still reporting "Unable to Load".

Figured it was weird since its showing different behavior on 2 different devices running the same Adguard test build.

**Comment by AleksandrShulgin** [comment]
@BaronKrause

**Comment by Quorum75** [comment]
Same here. However the widget works on iOS on iPhone but not on iPadOS.

**Comment by planet0** [comment]
Still occurring on 4.3.0(915)

**Comment by verdi1987** [comment]
Seeing the same on 4.3.0 release for iOS/iPadOS.

**Comment by Quorum75** [comment]
Problem still occurs with 4.3.1 (919).

**Comment by AleksandrShulgin** [comment]
@BaronKrause, @Quorum75, @planet0 
Could you please sent the logs to our email: devteam@adguard.com

**Comment by planet0** [comment]
I should also mention I sent through my logs on the 13th.

**Comment by ameshkov** [comment]
At the moment all the logs I received were from the stable version.

@Quorum75 could you please re-send them again, maybe I missed it somehow?
Please indicate your Github username in the email.

**Comment by planet0** [comment]
Not a problem. I just sent through another one with 4.3.2(923).

**Comment by ameshkov** [comment]
@planet0 please try build 925, it is the latest available one.

**Comment by planet0** [comment]
@ameshkov TestFlight is only showing me 4.3.2 (923) as the latest version. Do I need to wait for it to become available?

**Comment by ameshkov** [comment]
@planet0 weird stuff. We pushed it silently, but it seems that sending a notification to the testers is mandatory.

**Comment by planet0** [comment]
@ameshkov That is odd. It did however make 925 immediately available. Unfortunately, the widget hangs for about 3-4 seconds and then displays "Unable to Load" still. Would you like new logs sent with this build?

**Comment by ameshkov** [comment]
@planet0 yeah, in this version the widget writes more logs, it will be useful.

**Comment by planet0** [comment]
@ameshkov No problem, I still had debug logs enabled so I've been able to send you the logs immediately via email.

**Comment by ameshkov** [comment]
@planet0 thank you for the logs, it is helpful indeed. At least now we can see where exactly it stalls. In the next beta we'll make an attempt to fix this and also add a bit more logs just in case if the first attempt is not successful and we need more info.

**Comment by planet0** [comment]
@ameshkov Brilliant, thank you!

**Comment by ameshkov** [comment]
@planet0 could you please check it with the latest nightly? I am not entirely sure that the fix will help (there is a chance, though), but at least there will be enough logs to narrow it down further.

**Comment by planet0** [comment]
@ameshkov It sadly hasn't fixed the widget, so I have just sent new logs for you.

**Comment by Quorum75** [comment]
With AG Pro Beta 4.3.2 (930) the problem is solved 👍🏻

**Comment by planet0** [comment]
@ameshkov @Quorum75 Oh yes you are right, I quickly removed the widget and added it back and the widget loaded!

**Comment by planet0** [comment]
I've updated to iOS 15.3 and the widget is unable to load again. Sent new logs.

**Comment by ameshkov** [comment]
Argh. Hopefully, we'll push another beta today. With another attempt to improve this situation.

**Comment by planet0** [comment]
Just emailed through new logs for 4.3.2 (932) as the widget still isn't loading.

**Comment by ameshkov** [comment]
@planet0 even after re-adding it? Tbh, I am out of ideas for now:( 

The only kind of idea I have is that the widget code reuses services from the main process that are rather heavy. Changing this requires substantial changes in the code so I will reassign this issue to AG v4.5.

**Comment by planet0** [comment]
Still "Unable to Load" with 4.3.2 (933) — it feels like this only started as of 4.3.
@ameshkov not a problem, any help with testing let me know.

**Comment by Quorum75** [comment]
> Still "Unable to Load" with 4.3.2 (933) — it feels like this only started as of 4.3.
> 
> @ameshkov not a problem, any help with testing let me know.

I agree it started on 4.3.

**Comment by planet0** [comment]
I'm not sure of the reason, but the widget is now working for me.

I have changed from an iPhone SE (2020) to an iPhone 13, otherwise I haven't done anything else to have it working again.

**Comment by Goddess-Bastet** [comment]
Problem occurs for me on iPad Pro 9.7 running iOS 15.4.1.

**Comment by planet0** [comment]
Also found "Unable to Load" when using Native Implementation instead of AdGuard Implementation for DNS.

**Comment by planet0** [comment]
Instead of resolving this, it might be worth removing this classic widget, and create a new dynamic widget introduced in iOS 14. https://github.com/AdguardTeam/AdguardForiOS/issues/1641

**Comment by Domsicols** [comment]
Still occurring iPad os 16.1. Sent logs

**Comment by BaronKrause** [comment]
> Still occurring iPad os 16.1. Sent logs

Same, it works using the TestFlight version installed fresh on my new iPhone, but my existing iPad had it break and just endlessly display “unable to load” after uninstalling the App Store version and installing the TestFlight version. Uninstalling that version and going back to the App Store version did not fix it.

**Comment by Ribero** [comment]
Well, issue opened in December 2021, problem still occurs in April 2023 !
The unable to load issue on iPad is really annoying 
The fact that ADGuard still not updated the Widget part of the product to migrate to the new widget format is also… frustrating (to say it a positive way)

**Comment by jslawler** [comment]
There's been another occurrence [mentioned](https://forum.adguard.com/index.php?threads/ipad-unable-to-load-adguard-widget.52713/#post-229443) on the forums.

**Comment by Iridescentchris** [comment]
Works great on iOS 17; however, it’s still unable to load on iPadOS 17 ,which is really annoying. I hope this can be fixed soon.
