### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1858]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  AG Beta 4.3.0(876)
- **Device model and storage size:**
  -  iPad 11 Pro 256Gb
- **Operating system and version:**
  -  iPadOS 15.2
- **Browser or App:**
  - N/A

### Expected Behavior

 Application stability 

### Actual Behavior

 AG crashes in the background on random basis while the application is closed. 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

 Issue reported several through Testflight send feedback process

**Comment by AleksandrShulgin** [comment]
@Quorum75 Hi 
How often does this happened?
Did you perform any actions before this happened?

**Comment by jordanelliott23** [comment]
i get this also

**Comment by AleksandrShulgin** [comment]
@jordanelliott23 @Quorum75  have you updated to beta 2?

**Comment by AleksandrShulgin** [comment]
@Quorum75 
We've fixed the issue related to crashes in v.4.3.0 (915).
Please update and let us know if the problem happens again.

**Comment by Quorum75** [comment]
> @Quorum75 Hi 
> 
> How often does this happened?
> 
> Did you perform any actions before this happened?

Often. No action on AG or anything specific.

**Comment by Quorum75** [comment]
> @jordanelliott23 @Quorum75  have you updated to beta 2?

Update is automatic on iOS. I am now using 4.3.0 (915).

**Comment by Quorum75** [comment]
> @Quorum75 
> 
> We've fixed the issue related to crashes in v.4.3.0 (915).
> 
> Please update and let us know if the problem happens again.

Thanks, will do. 

BTW the issue of iOS widget not loading is still present since the first release of 4.3.0.
