### ISSUE TITLE
[BUG] Site in DNS white list not correctly works, always adblock detected!

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForiOS#1990]
iOS: 15.6 beta 2
AdGuard 4.4.0
DNS protection enabled using https Cloudflare dns.

If i put in DNS white list this site: **_iptvrun.com_** the site will still detect adguard.
If i disable DNS protection, the site will NOT detect adguard.

I have NOT this problem on adguard on mac.

How can i fix it? Is there a bug in DNS protecion that broke white list?

**Comment by michael1900** [comment]
iOS: 15.6 beta 1
AdGuard 4.4.0

**Comment by michael1900** [comment]
Added also this rule like on adguard on mac: **@@||iptvrun.com^$important,document** but nothing is changed.

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> Added also this rule like on adguard on mac: **@@||iptvrun.com^$important,document** but nothing is changed.

This worked for me, see below image.
![image](https://user-images.githubusercontent.com/95468948/169780159-0e1b10a5-ca1e-4010-b365-679c7acfdde0.png)

You'll probably find that your DNS filtering is blocking it. Try disabling that and test it again.

Besides that, I've also [raised this as a filtering issue](https://github.com/AdguardTeam/AdguardFilters/issues/119606). It should get resolved in the coming days.

**Comment by michael1900** [comment]
Hi, without DNS filtering enabled seems it work but i can't keep that disabled. The white list in DNS filtering is not working?

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> Hi, without DNS filtering enabled seems it work but i can't keep that disabled. The white list in DNS filtering is not working?

It depends what DNS server you're using, and where the filtering is happening.
If for example you're using AdGuard DNS (filtered), the user rule won't apply here.
If you're using AdGuard DNS (unfiltered) with the filter list locally on your device, the user rule will apply here.

**Comment by michael1900** [comment]
I tried with AG dns unfiltered, standard locally list already enabled and iptvrun.com in white list but problem is still there. I tried with different dns but nothing changed. For example now i am using Cloudflare DNS + locally list dns + iptvrun.com in white list but problem is the same.

**Comment by michael1900** [comment]
Seems fixed now with one of filters update. No need to move the site adrress in white list.

**Comment by michael1900** [comment]
> > _Seems_ fixed now with one of filters update. No need to move the site adrress in white list.
> > EDIT: errata corridge. iptvrun.com site still detects the DNS filter. If i put the site in whitelist both safari and dns nothing changes. How to fix? Thanks
> 
> Of course, the issue I raised on GitHub for you in the link above still hasn't been closed yet.

Sorry but in the issue that you opened i see: DNS disabled 
Do you mean that i MUST disable the dns filter/protection to see that site?

**Comment by michael1900** [comment]
UP!

**Comment by Alex-302** [comment]
@michael1900 https://kb.adguard.com/en/technical-support/reporting-tool#ios
