### ISSUE TITLE
Incorrect display of DNS server

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForiOS#949]
Incorrect display of DNS server name:

DNS-over-TLS
![img](https://uploads.adguard.com/TheHasagi06cal.jpg)
DNS-over-HTTPS
![img](https://uploads.adguard.com/TheHasagiws24m.jpg)

**Comment by IvanIin** [comment]
fixed in 126

**Comment by F3000** [comment]
Which version is 126 ? Build ?

**Comment by ameshkov** [comment]
@F3000 it's 3.0 build 126. Currently, it's in internal testing

**Comment by ameshkov** [comment]
@IvanIin not fully fixed. It now displays ` - Regular` instead of the custom DNS server name. You should simply print its name without protocol.
